#![allow(unexpected_cfgs)]
use borsh::{BorshDeserialize,BorshSerialize};
use solana_program::{account_info::{next_account_info,AccountInfo},entrypoint,entrypoint::ProgramResult,program::invoke_signed,program_error::ProgramError,pubkey::Pubkey,rent::Rent,system_instruction,sysvar::Sysvar};
solana_program::declare_id!("5TeWSsjg2gbxCyWVniXeCmwM7UtHTCK7svzJr5xYJzHf"); entrypoint!(entry);
#[derive(BorshSerialize,BorshDeserialize,Debug,PartialEq)] pub struct Network{pub version:u8,pub authority:Pubkey,pub settlement_count:u64,pub settled_lamports:u64,pub paused:bool,pub bump:u8}
impl Network{pub const VERSION:u8=1;pub const LEN:usize=1+32+8+8+1+1;}
pub fn entry(pid:&Pubkey,a:&[AccountInfo],input:&[u8])->ProgramResult{let(&tag,rest)=input.split_first().ok_or(ProgramError::InvalidInstructionData)?;let i=&mut a.iter();match tag{
0=>{let auth=next_account_info(i)?;let network=next_account_info(i)?;let system=next_account_info(i)?;if !auth.is_signer{return Err(ProgramError::MissingRequiredSignature)}let(pda,bump)=Pubkey::find_program_address(&[b"network",auth.key.as_ref()],pid);if pda!=*network.key{return Err(ProgramError::InvalidSeeds)}let rent=Rent::get()?;invoke_signed(&system_instruction::create_account(auth.key,network.key,rent.minimum_balance(Network::LEN),Network::LEN as u64,pid),&[auth.clone(),network.clone(),system.clone()],&[&[b"network",auth.key.as_ref(),&[bump]]])?;Network{version:Network::VERSION,authority:*auth.key,settlement_count:0,settled_lamports:0,paused:false,bump}.serialize(&mut &mut network.data.borrow_mut()[..])?;Ok(())},
1=>{let auth=next_account_info(i)?;let network=next_account_info(i)?;if !auth.is_signer{return Err(ProgramError::MissingRequiredSignature)}if network.owner!=pid{return Err(ProgramError::IllegalOwner)}let mut n=Network::try_from_slice(&network.data.borrow()).map_err(|_|ProgramError::InvalidAccountData)?;if n.authority!=*auth.key{return Err(ProgramError::MissingRequiredSignature)}n.paused=!n.paused;n.serialize(&mut &mut network.data.borrow_mut()[..])?;Ok(())},
2 if rest.len()==8=>{let network=next_account_info(i)?;let auth=next_account_info(i)?;let _payment=next_account_info(i)?;if !auth.is_signer{return Err(ProgramError::MissingRequiredSignature)}if network.owner!=pid{return Err(ProgramError::IllegalOwner)}let mut n=Network::try_from_slice(&network.data.borrow()).map_err(|_|ProgramError::InvalidAccountData)?;if n.authority!=*auth.key||n.paused{return Err(ProgramError::InvalidAccountData)}let amount=u64::from_le_bytes(rest.try_into().unwrap());if amount==0{return Err(ProgramError::InvalidArgument)}n.settlement_count=n.settlement_count.checked_add(1).ok_or(ProgramError::ArithmeticOverflow)?;n.settled_lamports=n.settled_lamports.checked_add(amount).ok_or(ProgramError::ArithmeticOverflow)?;n.serialize(&mut &mut network.data.borrow_mut()[..])?;Ok(())},_=>Err(ProgramError::InvalidInstructionData)}}
#[cfg(test)]mod tests{use super::*;#[test]fn len_matches(){let n=Network{version:1,authority:Pubkey::new_unique(),settlement_count:2,settled_lamports:9,paused:false,bump:255};assert_eq!(borsh::to_vec(&n).unwrap().len(),Network::LEN)}}
